import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Acceptable Use Policy - Plushify",
  description:
    "Guidelines for acceptable use of the Plushify image transformation service.",
};

export default function AcceptableUsePolicyPage() {
  return (
    <>
      <header className="mb-8 pb-8 border-b">
        <h1 className="font-bold tracking-tight mb-2">Acceptable Use Policy</h1>
        <p className="text-sm text-muted-foreground">
          Last Updated: January 26, 2026
        </p>
      </header>

      <p className="lead">
        This Acceptable Use Policy (&quot;AUP&quot;) outlines the rules and
        guidelines for using the Plushify service. By using Plushify, you agree
        to comply with this policy. Violations may result in content removal,
        account suspension, or termination.
      </p>

      <h2 id="purpose">1. Purpose</h2>
      <p>
        Plushify is designed to create fun, family-friendly plushie
        transformations of images. Our goal is to maintain a safe, positive
        environment for all users while protecting the integrity of our service
        and respecting the rights of others.
      </p>
      <p>
        This policy applies to all content uploaded to, generated by, or shared
        through the Plushify service.
      </p>

      <h2 id="prohibited-content">2. Prohibited Content</h2>
      <p>
        You may not upload, submit, or use images to generate content that falls
        into any of the following categories:
      </p>

      <h3>Illegal Content</h3>
      <ul>
        <li>Content that violates any applicable local, state, national, or international law</li>
        <li>Content depicting illegal activities or promoting illegal conduct</li>
        <li>Content that infringes on intellectual property rights (copyright, trademark, etc.)</li>
        <li>Content related to illegal drugs or controlled substances</li>
      </ul>

      <h3>Harmful or Abusive Content</h3>
      <ul>
        <li>Content that promotes violence, terrorism, or physical harm</li>
        <li>Content that harasses, bullies, intimidates, or threatens others</li>
        <li>Content that promotes discrimination based on race, ethnicity, religion, gender, sexual orientation, disability, or other protected characteristics</li>
        <li>Content that glorifies or promotes self-harm or suicide</li>
      </ul>

      <h3>Sexual or Adult Content</h3>
      <ul>
        <li>Sexually explicit or pornographic content</li>
        <li>Content depicting nudity intended to be sexual in nature</li>
        <li>Content depicting sexual acts or suggestive poses</li>
        <li>Content intended to sexualize individuals</li>
      </ul>

      <h3>Content Involving Minors</h3>
      <ul>
        <li>Any content that exploits or endangers minors</li>
        <li>Content depicting minors in inappropriate situations</li>
        <li>Child sexual abuse material (CSAM) - <strong>Zero tolerance. Reported to authorities immediately.</strong></li>
      </ul>

      <h3>Deceptive or Fraudulent Content</h3>
      <ul>
        <li>Content created for impersonation or identity fraud</li>
        <li>Deepfakes or manipulated media intended to deceive</li>
        <li>Content used for scams, phishing, or financial fraud</li>
        <li>Misinformation or disinformation intended to mislead</li>
      </ul>

      <h3>Privacy Violations</h3>
      <ul>
        <li>Images of individuals uploaded without their consent</li>
        <li>Content that reveals private information (doxing)</li>
        <li>Content obtained through unauthorized access or hacking</li>
      </ul>

      <h2 id="prohibited-activities">3. Prohibited Activities</h2>
      <p>
        In addition to content restrictions, the following activities are
        prohibited:
      </p>

      <h3>Service Abuse</h3>
      <ul>
        <li>
          <strong>Automated Access:</strong> Using bots, scrapers, or automated
          tools to access the service without authorization
        </li>
        <li>
          <strong>Reverse Engineering:</strong> Attempting to reverse engineer,
          decompile, or extract our AI models, algorithms, or source code
        </li>
        <li>
          <strong>Circumvention:</strong> Bypassing security measures, rate
          limits, or usage restrictions
        </li>
        <li>
          <strong>API Abuse:</strong> Excessive API calls or attempting to
          overwhelm our systems
        </li>
      </ul>

      <h3>Account Violations</h3>
      <ul>
        <li>
          <strong>Multiple Accounts:</strong> Creating multiple accounts to
          evade restrictions or abuse promotions
        </li>
        <li>
          <strong>Account Sharing:</strong> Sharing account credentials with
          others without authorization
        </li>
        <li>
          <strong>Account Selling:</strong> Selling or transferring accounts or
          credits
        </li>
        <li>
          <strong>Impersonation:</strong> Creating accounts that impersonate
          others or Plushify staff
        </li>
      </ul>

      <h3>Commercial Misuse</h3>
      <ul>
        <li>Reselling generated images without appropriate licensing</li>
        <li>Using the service for unauthorized commercial purposes</li>
        <li>White-labeling our service without partnership agreement</li>
        <li>Mass-producing content for spam or low-quality applications</li>
      </ul>

      <h3>Interference</h3>
      <ul>
        <li>Attempting to disrupt or interfere with the service</li>
        <li>Introducing malware, viruses, or harmful code</li>
        <li>Engaging in denial-of-service attacks</li>
        <li>Exploiting bugs or vulnerabilities (report them instead!)</li>
      </ul>

      <h2 id="content-guidelines">4. Content Guidelines</h2>
      <p>
        For the best experience and to ensure compliance, please follow these
        guidelines:
      </p>

      <h3>Recommended Content</h3>
      <ul>
        <li>Personal photos of yourself, friends, family (with their consent)</li>
        <li>Pet photos</li>
        <li>Artwork or original creations you have rights to</li>
        <li>Stock images with appropriate licenses</li>
        <li>Public domain images</li>
      </ul>

      <h3>Best Practices</h3>
      <ul>
        <li>
          <strong>Get Consent:</strong> Always obtain permission before
          uploading images of other people
        </li>
        <li>
          <strong>Respect Copyright:</strong> Only use images you own or have
          rights to use
        </li>
        <li>
          <strong>Consider Context:</strong> Think about how the plushified
          result might be perceived
        </li>
        <li>
          <strong>Keep It Fun:</strong> Plushify is meant for lighthearted,
          creative use
        </li>
      </ul>

      <h2 id="enforcement">5. Enforcement</h2>
      <p>
        We take violations of this policy seriously and may take the following
        actions:
      </p>

      <h3>Content Actions</h3>
      <ul>
        <li>
          <strong>Content Removal:</strong> Violating content will be removed
          without refund of credits used
        </li>
        <li>
          <strong>Generation Blocking:</strong> Flagged content may be blocked
          from processing
        </li>
        <li>
          <strong>Gallery Restrictions:</strong> Violating content may be
          removed from your gallery
        </li>
      </ul>

      <h3>Account Actions</h3>
      <ul>
        <li>
          <strong>Warning:</strong> First-time or minor violations may result in
          a warning
        </li>
        <li>
          <strong>Temporary Suspension:</strong> Repeated or serious violations
          may result in temporary account suspension
        </li>
        <li>
          <strong>Permanent Ban:</strong> Severe or repeated violations will
          result in permanent account termination
        </li>
        <li>
          <strong>Credit Forfeiture:</strong> Remaining credits may be forfeited
          upon account termination for policy violations
        </li>
      </ul>

      <h3>Legal Actions</h3>
      <ul>
        <li>
          <strong>Law Enforcement:</strong> Illegal content or activities will
          be reported to appropriate authorities
        </li>
        <li>
          <strong>CSAM Reporting:</strong> Child sexual abuse material is
          reported to NCMEC and law enforcement immediately
        </li>
        <li>
          <strong>Legal Claims:</strong> We may pursue legal action for damages
          caused by policy violations
        </li>
      </ul>

      <h2 id="appeals">6. Appeals Process</h2>
      <p>If you believe enforcement action was taken in error:</p>
      <ol>
        <li>
          <strong>Contact Support:</strong> Email{" "}
          <Link href="mailto:appeals@plushify.com">appeals@plushify.com</Link>{" "}
          within 14 days of the action
        </li>
        <li>
          <strong>Provide Context:</strong> Explain why you believe the decision
          was incorrect
        </li>
        <li>
          <strong>Review:</strong> A different team member will review your
          appeal
        </li>
        <li>
          <strong>Decision:</strong> You will receive a response within 10
          business days
        </li>
      </ol>
      <p>Appeal decisions are final.</p>

      <h2 id="reporting">7. Reporting Violations</h2>
      <p>
        If you encounter content or behavior that violates this policy, please
        report it:
      </p>
      <ul>
        <li>
          <strong>Email:</strong>{" "}
          <Link href="mailto:abuse@plushify.com">abuse@plushify.com</Link>
        </li>
        <li>
          <strong>In-App:</strong> Use the &quot;Report&quot; button on any
          shared content
        </li>
      </ul>
      <p>When reporting, please include:</p>
      <ul>
        <li>A description of the violation</li>
        <li>URL or location of the content (if applicable)</li>
        <li>Screenshots or evidence (if available)</li>
        <li>Your contact information for follow-up</li>
      </ul>
      <p>
        We review all reports promptly and take appropriate action. Reports are
        kept confidential.
      </p>

      <h2 id="responsible-ai">8. Responsible AI Use</h2>
      <p>
        As an AI-powered service, we are committed to responsible AI use:
      </p>
      <ul>
        <li>
          <strong>Content Moderation:</strong> We employ automated systems to
          detect prohibited content
        </li>
        <li>
          <strong>Human Review:</strong> Flagged content is reviewed by trained
          moderators
        </li>
        <li>
          <strong>Continuous Improvement:</strong> We regularly update our
          systems to address new abuse patterns
        </li>
        <li>
          <strong>Transparency:</strong> We are open about our content policies
          and enforcement
        </li>
      </ul>

      <h2 id="updates">9. Policy Updates</h2>
      <p>
        We may update this Acceptable Use Policy from time to time. Significant
        changes will be communicated through:
      </p>
      <ul>
        <li>Email notification to registered users</li>
        <li>Prominent notice on our website</li>
        <li>In-app notification</li>
      </ul>
      <p>
        Continued use of the service after policy updates constitutes acceptance
        of the revised policy.
      </p>

      <h2 id="contact">10. Contact Us</h2>
      <p>If you have questions about this Acceptable Use Policy:</p>
      <ul>
        <li>
          <strong>General Questions:</strong>{" "}
          <Link href="mailto:support@plushify.com">support@plushify.com</Link>
        </li>
        <li>
          <strong>Report Violations:</strong>{" "}
          <Link href="mailto:abuse@plushify.com">abuse@plushify.com</Link>
        </li>
        <li>
          <strong>Appeals:</strong>{" "}
          <Link href="mailto:appeals@plushify.com">appeals@plushify.com</Link>
        </li>
      </ul>

      <p className="mt-8 text-sm">
        This Acceptable Use Policy is part of our{" "}
        <Link href="/terms">Terms of Service</Link>. Please also review our{" "}
        <Link href="/privacy">Privacy Policy</Link> to understand how we handle
        your information.
      </p>
    </>
  );
}
